apiVersion: apps/v1
kind: Deployment
metadata:
  name: erebor
  namespace: world
  labels:
    app: erebor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: erebor
  template:
    metadata:
      labels:
        app: erebor
    spec:
      containers:
        - name: erebor
          image: tdeslauriers/erebor:latest
          ports:
            - containerPort: 8443
          env:
            - name: EREBOR_SERVICE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: cm-gateway-service
                  key: gateway-client-id
            - name: EREBOR_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: cm-gateway-service
                  key: gateway-k8-port
            - name: EREBOR_CA_CERT
              valueFrom:
                secretKeyRef:
                  name: secret-server-ca-prod
                  key: server-ca-cert
            - name: EREBOR_SERVER_CERT
              valueFrom:
                secretKeyRef:
                  name: secret-gateway-server-cert
                  key: server-cert
            - name: EREBOR_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-gateway-server-cert
                  key: server-key
            - name: EREBOR_CLIENT_CERT
              valueFrom:
                secretKeyRef:
                  name: secret-gateway-client-cert
                  key: client-cert
            - name: EREBOR_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-gateway-client-cert
                  key: client-key
            - name: EREBOR_S2S_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: cm-s2s-service
                  key: s2s-auth-url
            - name: EREBOR_S2S_AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secret-gateway-s2s-client-creds
                  key: s2s-auth-client-id
            - name: EREBOR_S2S_AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-gateway-s2s-client-creds
                  key: s2s-auth-client-secret
            - name: EREBOR_DB_CA_CERT
              valueFrom:
                secretKeyRef:
                  name: secret-db-ca-prod
                  key: db-ca-cert
            - name: EREBOR_DB_CLIENT_CERT
              valueFrom:
                secretKeyRef:
                  name: secret-gateway-db-client-cert
                  key: client-cert
            - name: EREBOR_DB_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-gateway-db-client-cert
                  key: client-key
            - name: EREBOR_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: cm-gateway-db
                  key: db-url
            - name: EREBOR_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: cm-gateway-db
                  key: db-name
            - name: EREBOR_DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cm-gateway-db
                  key: db-username
            - name: EREBOR_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-gateway-db
                  key: db-password
            - name: EREBOR_DATABASE_HMAC_INDEX_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-gateway-db
                  key: hmac-index-secret
            - name: EREBOR_FIELD_LEVEL_AES_GCM_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-gateway-db
                  key: aes-gcm-secret
            - name: EREBOR_USER_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: cm-identity-service
                  key: identity-url
            - name: EREBOR_USER_JWT_VERIFYING_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-identity-jwt-signing
                  key: jwt-verifying-key
            - name: EREBOR_OAUTH_CALLBACK_URL
              valueFrom:
                configMapKeyRef:
                  name: cm-gateway-oauth-callback
                  key: oauth-callback-url
            - name: EREBOR_OAUTH_CALLBACK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: cm-gateway-oauth-callback
                  key: oauth-callback-client-id
            - name: EREBOR_TASKS_URL
              valueFrom:
                configMapKeyRef:
                  name: cm-allowance-service
                  key: allowance-url
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
